### ISSUE TITLE
GraphRagConfig in essex-config

### ISSUE THREAD

**Issue by andresmor-ms** [microsoft/essex-toolkit#277]
This issue is to track and discuss if GraphRagConfig should be tested inside of essex-config python package instead of #276

**Comment by AlonsoGuevara** [comment]
Thanks for opening this issue.
I consider having all of GraphRAG{s config in essex-config a bad approach.
If we want to test functionally of the essex-config library we should focus on edge cases and proper coverage. Adding GraphRAG introduces a lot of objects, concepts and such that are irrelevant for the config library.

If what we want to test is that GraphRAG can work with essex-config it should be the other way arounf and we then migrate and test in the proper package. GraphRAG should be irrelevant or unknown to essex-config.

**Comment by darthtrevino** [comment]
Closing this out since it's OBE
