### ISSUE TITLE
[essex-config] Support for typing.Literal

### ISSUE THREAD

**Issue by rracanicci** [microsoft/essex-toolkit#307]
If we try to use essex-config models with typing.Literal values (generally combined with booleans for discriminator types), we get a parsing error back:

`Cannot convert [True] to type [typing.Literal[True]].`

Sample model:

```python
class SampleModel(
    BaseModel, frozen=True, extra="allow", protected_namespaces=()
): 
    azure: Literal[True] = Field(default=True)
```

**Comment by andresmor-ms** [comment]
It seems to be working for me on #308
